{
  imports = [
    ../../base/gui
    ../base
    ./caffeine.nix
    ./dunst.nix
    ./easyeffects.nix
    ./gtk
    ./i3
    ./packages.nix
    ./picom.nix
    ./polybar.nix
    ./redshift.nix
    ./rofi.nix
    ./syncthing.nix
    ./urxvt.nix
    ./xinitrc.nix
    ./xprofile.nix
    ./xresources.nix
    ./zprofile.nix
  ];
}
