#! /usr/bin/env sh

# Get borg passphrase
export BORG_PASSPHRASE="$(gpg -d $HOME/.secrets/borg-passphrase.gpg 2>/dev/null)"

# Create backup archive
sudo -E borg create \
  --rsh "ssh -i ~/.ssh/id_rsa -p 222" \
  -spC zstd \
  --exclude-from ~/Documents/backup-exclude.txt \
  $1::$(hostname)-$(date --iso-8601) /
