#! /usr/bin/env sh

PASS_FILE="$HOME/.secrets/fde-passphrase.gpg"

# Get LUKS passphrase and open LUKS partition
[ -f "$PASS_FILE" ] &&
gpg --batch -d "$PASS_FILE" 2>/dev/null |
sudo cryptsetup open --type luks "$1" backup ||
sudo cryptsetup open --type luks "$1" backup &&


sudo mount /dev/mapper/backup /mnt &&
backup /mnt

# Clean up
sudo umount /mnt >/dev/null
sudo cryptsetup close /dev/mapper/backup >/dev/null
