#! /usr/bin/env sh

# Get LUKS passphrase and open LUKS partition
gpg --batch -d $HOME/.secrets/fde-passphrase.gpg 2>/dev/null |
sudo cryptsetup open --type luks $1 backup && \

sudo mount /dev/mapper/backup /mnt && \
backup /mnt

# Clean up
sudo umount /mnt >/dev/null
sudo cryptsetup close /dev/mapper/backup >/dev/null
