#!/bin/sh

i3lock \
    --indicator \
    --ind-pos "x+75:y+75" \
    --radius 15 \
    --ring-color "ffffffff" \
    --ringver-color "ff906bff" \
    --ringwrong-color "f46060ff" \
    --separator-color "00000000" \
    --inside-color "00000000" \
    --insidever-color "00000000" \
    --insidewrong-color "00000000" \
    --line-uses-inside \
    --verif-text "" \
    --wrong-text "" \
    --force-clock \
    --time-pos "ix+50:iy" \
    --time-color "ffffffff" \
    --time-str "%H:%M:%S" \
    --time-align 1 \
    --date-str "%A, %F" \
    --date-color "ffffffff" \
    --date-align 1 \
    --pass-media-keys \
    --pass-volume-keys \
    --pass-screen-keys \
    --pass-power-keys \
    --blur 8
